version: 0.2
phases:
  install:
    commands:
      - echo Install started on `date`
      - echo Entering install phase...
      - uname -a
      - yum install java-17-amazon-corretto-headless -y
      - java -version
      - echo "Updating alternatives for java and java compiler"
      - update-alternatives --config java /usr/lib/jvm/java-17-amazon-corretto.x86_64/bin/java
      - update-alternatives --config javac /usr/lib/jvm/java-17-amazon-corretto.x86_64/bin/javac
  build:
    commands:
      - echo Build started on `date`
      - chmod +x ./gradlew
      - ./gradlew bootJar
artifacts:
  files:
    - 'build/libs/*.jar'
  discard-paths: yes
