version: 0.2
phases:
  install:
    commands:
      - echo Install started on `date`
      - echo Entering install phase...
      - uname -a
      - yum update -y
      - echo list available openjdk packages
      - yum list *openjdk*
      - echo install openjdk packages      
      - yum install java-17-amazon-corretto-headless
  build:
    commands:
      - echo Build started on `date`
      - chmod +x ./gradlew
      - ./gradlew bootJar
artifacts:
  files:
    - 'build/libs/*.jar'
  discard-paths: yes
