version: 0.2
phases:
  install:
    commands:
      - echo Install started on `date`
      - echo Entering install phase...
      - uname -a
      - yum remove java-11-amazon-corretto-headless -y
      - yum remove java-8-amazon-corretto-headless -y
      - yum install java-17-amazon-corretto-headless -y
  build:
    commands:
      - echo Build started on `date`
      - chmod +x ./gradlew
      - ./gradlew bootJar
artifacts:
  files:
    - 'build/libs/*.jar'
  discard-paths: yes
