version: 0.1

phases:
  install:
    commands:
      - echo Install started on `date`
      - echo Entering install phase...
      - echo Nothing to do now
  build:
    commands:
      - ls -al
      - echo Build started on `date`
      - gradlew bootJar
artifacts:
  type: zip
  files:
    - 'build/libs/*.jar'
