version: 0.2
phases:
  install:
    commands:
      - echo Install started on `date`
      - echo Entering install phase...
      - uname -a
      - yum install java-17-amazon-corretto-headless -y
      - java -version
      - alternatives --config java <<< '2'
      - java -version
  build:
    commands:
      - echo Build started on `date`
      - chmod +x ./gradlew
      - ./gradlew bootJar
artifacts:
  files:
    - 'build/libs/*.jar'
  discard-paths: yes
