version: 0.2

phases:
  install:
      - yum install java-17-amazon-corretto-headless
    commands:
      - echo Install started on `date`
      - echo Entering install phase...
      - echo Nothing to do now
  build:
    commands:
      - echo Build started on `date`
      - ls -al
      - ./gradlew bootJar
artifacts:
  type: zip
  files:
    - 'build/libs/*.jar'
